services:
  - type: web
    name: glucoai-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: MPLBACKEND
        value: Agg
